### ISSUE TITLE
ActiveSupport 3.0 issues?

### ISSUE THREAD

**Issue by scsmith** [peritor/happening#1]
Hey, I'm getting a bunch of errors caused by using active_support 3.0 rather than 2.x the thing is I can't for the life of me figure out whats going on. It's methods like assert_valid_keys and symbolize_keys on the hash and present? on the string.

Its clearly the method overrides that are in active_support but I can't get things to work unless I say gem 'active_support', '=2.0.x' before calling require. The weird thing is that the hash file especially doesn't appear to have been changed in Rails in the move to 3.0. Does anyone with any more knowledge on the changes that occured have a solution?

**Comment by jweiss** [comment]
Yeah, ActiveSupport 3.0 doesn't load those extensions by default. Can you give 0.1.0 a try?

**Comment by scsmith** [comment]
Works for me. It's always simple isn't it I was just missing the core extensions. Thanks!
