### ISSUE TITLE
require 'time' is needed for httpdate

### ISSUE THREAD

**Issue by scsmith** [peritor/happening#2]
Hey I was getting an error:

```
undefined method `httpdate' for 2011-02-11 15:27:13 +0000:Time
...bundle/ruby/1.9.1/gems/happening-0.1.0/lib/happening/aws.rb:18:in `sign'
...bundle/ruby/1.9.1/gems/happening-0.1.0/lib/happening/s3/item.rb:107:in `construct_aws_headers'
...bundle/ruby/1.9.1/gems/happening-0.1.0/lib/happening/s3/item.rb:39:in `put'
```

After updating updating my bundle containing happening (only active support plus deps and json gems changed). I'm guessing active support used to require it and doesn't now?

Adding require 'time' to my code fixed it but I'm guessing time should really be required by the aws file?

**Comment by jweiss** [comment]
fixed with https://github.com/peritor/happening/commit/b406f81615185f7e39019be87d2ba19545c8a9d5
